CommitMsg:
  AddTicketId:
    enabled: true

PreCommit:
  KtLint:
    enabled: true
    description: 'Analyze with KtLint'
    required_executable: 'ktlint'
    flags: []
    include: '**/*.kt'
    install_command: 'brew install ktlint'

PrePush:
  # This uses pre-push hook for ruby, but changes command to actually be gradle
  # Implementation of these hooks does nothing special, and would be same if GradleTest were implemented
  TestUnit:
    enabled: true
    description: 'Run gradle test suite'
    command: ['./gradlew', ':app:testDebugUnitTest']

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes

verify_signatures: false
