name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install ktlint
      run: brew install ktlint
    - name: Run ktlint
      run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report-in-checkstyle-format.xml
    - uses: yutailang0119/action-ktlint@v1.0.0
      with:
        xml_path: build/ktlint-report-in-checkstyle-format.xml
    - name: Generate dummy configurations
      run: cp app/config-example.properties app/debug.properties && cp app/config-example.properties app/release.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Android Lint with Gradle
      run: ./gradlew lint
    - uses: yutailang0119/action-android-lint@v1.0.2
      with:
        xml_path: build/reports/lint-results.xml
    - name: Build with Gradle
      run: ./gradlew build
